[package]
name = "syncr-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa-trees = { version = "0.7.0", features = ["serde"] }
fast_rsync = "0.2.0"
linfa = { version = "0.7.0", features = ["serde"] }
# linfa-linear = { version = "0.7.0", features = ["serde"] }
ndarray = { version = "0.15" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
anyhow = "1.0.93"
rand = "0.8.5"
rustls = "0.23.16"
tokio = { version = "1.41.1", features = ["full"] }
dirs = "5.0.1"
rcgen = "0.9"
tokio-rustls = "0.26.0"
rayon = "1.10.0"
futures = "0.3.31"
ignore = "0.4.23"
ring = "0.17.8"
hex = "0.4.3"
bytes = "1.8.0"
cmp = "0.1.0"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
