[package]
name = "syncr-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa-trees = { version = "0.7.0", features = ["serde"] }
fast_rsync = "0.2.0"
linfa = { version = "0.7.0", features = ["serde"] }
linfa-linear = { version = "0.7.0", features = ["serde"] }
ndarray = { version = "0.15" }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
zstd = "0.13.2"
anyhow = "1.0.91"
rand = "0.8.5"
