[config]
secret = ""
auto-wonder = true
mode = "client"

[config.client]
server-ip = "127.0.0.1"
server-port = 7878

[[config.client.directories]]
path = "~/Documents/directory"
active = true

[[config.client.directories]]
path = "~/Downloads/gustavo"
active = true
